version: '3.8'
services:

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/code/app

  streamlit:
    build:
      context: ./streamlit  # Set the build context to the streamlit directory
      dockerfile: Dockerfile  # Use the Dockerfile in the streamlit directory
    volumes:
      - ./streamlit/app:/code/app
      - ./streamlit/assets:/content
      - ./ee_creds:/root/.config/earthengine/credentials
    ports:
      - "5000:5000"
