- name: Ensure mokutil is installed
  apt:
    name: mokutil
    state: present
  become: yes

- name: Check if Secure Boot is enabled
  command: mokutil --sb-state
  register: secure_boot_status
  changed_when: False
  failed_when: "'SecureBoot enabled' in secure_boot_status.stdout"

- name: Show Secure Boot status
  debug:
    var: secure_boot_status.stdout_lines

- name: Add driver repo
  apt_repository:
    repo: ppa:graphics-drivers
    state: present
  become: yes

- name: Install graphic drivers
  apt:
    update_cache: yes
    name:
      - nvidia-driver-440
  register: installNvidiaGraphicsDriver

- name: Reboot the machine
  reboot:
  when: installNvidiaGraphicsDriver.changed
