- name: Ensure /etc/docker directory exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0755'
- name: Upload daemon.json configuration to remote
  ansible.builtin.copy:
    content: |
      {
        "default-address-pools": [
          {"base": "172.17.0.0/16", "size": 24}
        ],
        "data-root": "/docker"
      }
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'

- name: Restart docker
  shell: systemctl restart docker
